### ISSUE TITLE
problem with cluster role

### ISSUE THREAD

**Issue by didlawowo** [akyriako/kube-dosbox#2]
the cluster role is incorrect

the correct api for deployment is apps

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - persistentvolumeclaims
  - pods
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - "apps"
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.contrib.dosbox.com
  resources:
  - games
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.contrib.dosbox.com
  resources:
  - games/finalizers
  verbs:
  - update
- apiGroups:
  - operator.contrib.dosbox.com
  resources:
  - games/status
  verbs:
  - get
  - patch
  - update
```
